project_ref = "nhscvoqyjtpaskeqaths"
api_url = "https://mzzwhrmciijyuqtfgtgg.supabase.co"
anon_key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im16endocm1jaWlqeXVxdGZndGdnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njk2NjM2MTQsImV4cCI6MjA4NTIzOTYxNH0.TGndaUPj0roEIHdTnEjigM4PVCeUNVzr1zDPYoFkJ-0"